### ISSUE TITLE
Server files transpiled by Babel do not run (import statements not natively supported by Node)

### ISSUE THREAD

**Issue by MattSidor** [haochuan/create-express-react#2]
There is no transpilation preset defined in either the npm script `buildServer`, or in a `.babelrc` file, so Babel doesn't actually do any transpilation of the built files that get produced in the `dist` folder.

As a result, I immediately get an error on the first line of `dist/index.js` because `import` statements are not natively supported (yet) by nodejs.

Unfortunately, I am also having issues when I create a `.babelrc` file with presets that should work, like:

    {
      "presets": ["es2015"]
    }

The first error I get is related to the `server/config/env.js` file; it doesn't seem to import correctly:

    if (_env2.default.name === "production") {
                  ^
    
    TypeError: Cannot read property 'name' of undefined
        at Object.<anonymous> (/Users/msidor/Documents/fmeco/ceed/dist/app.js:80:19)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)
        at Function.Module._load (module.js:489:3)
        at Module.require (module.js:579:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/msidor/Documents/fmeco/ceed/dist/index.js:7:12)
        at Module._compile (module.js:635:30)

I'm inexperienced with Babel, so I could use some help to figure out the correct configuration for this repository.

@haochuan, have you been able to get the `build` script to run correctly on your machine?

**Comment by MattSidor** [comment]
I figured this out - the babel transpiler is working when the configuration is set properly, I just didn't have the NODE_ENV variable set. When it's set, it works fine.

I'm going to close this issue and I'll create a pull request for the `.babelrc` file later today.

**Comment by MattSidor** [comment]
Alright, there *is* a `.babelrc` file that gets built out with this library. I don't know why mine was missing. So sorry for the false alarm!
